name: Convert Markdown to Text

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y pandoc

    - name: Convert Markdown to Text
      run: |
        find . -type f -name "*.md" | while read -r mdfile; do
          txtfile="${mdfile%.md}.txt"
          txtdir="txt/$(dirname "$txtfile")"
          mkdir -p "$txtdir"
          pandoc "$mdfile" -o "$txtdir/$(basename "$txtfile")"
        done

    - name: Commit and Push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add txt/
        git commit -m "Convert Markdown files to Text"
        git push

    - name: Upload TXT Files as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: converted-txt-files
        path: txt/
